# Generated by Django 4.2.7 on 2023-11-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Praise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("praised_to", models.CharField(max_length=100)),
                ("praised_by", models.CharField(max_length=100)),
                ("praise_text", models.TextField()),
                ("image", models.ImageField(upload_to="praise_images/")),
                ("badge_icon", models.ImageField(upload_to="badge_icons/")),
            ],
        ),
    ]
